### ISSUE TITLE
Use EC brainpoolP256r1 key for encryption/decryption

### ISSUE THREAD

**Issue by akalongman** [paragonie/halite#173]
Can I use EC brainpoolP256r1 for encryption/decryption? Key generated by OpenSSL:
```
openssl ecparam -name brainpoolP256r1 -genkey -noout -out private.key
```

How to load such keys for usage in Halite?  `KeyFactory::loadEncryptionKey('private.key');` throws error "Expected hexadecimal character"

**Comment by paragonie-security** [comment]
No, you cannot use other elliptic curves with Halite. Please only use keys generated by Halite with Halite.

The curve Halite uses is Ed25519 (for signatures) and X25519 (for key agreement).

**Comment by akalongman** [comment]
@paragonie-security could you give me any suggestion what can I use on PHP?

**Comment by paragonie-security** [comment]
What do you mean by what you can "use on PHP"?

Halite is a PHP library that makes encryption, signing, etc. drop-dead simple. It's very hard to screw Halite up. 

If you want to use a nonstandard curve like Brainpool's in PHP, first explain why you need that curve in particular. Otherwise, this is an [XY problem](https://xyproblem.info/).

Do you need to interoperate with a specific appliance that only uses that curve? If so, demand the vendor of that appliance provide a library you can use.

Otherwise, stop worrying about weird curves and just use Ed25519/X25519, the elliptic curves for security. If you want an easy time using those in PHP, without ever having to delve in to the guts of an application, that's where Halite comes in. If you want to tinker, just use libsodium directly.

**Comment by akalongman** [comment]
Vendor provided only .Net/Java libraries :( So, I have to implement it on PHP. 
Is it possible to use Brainpool using libsodium directly? Without Halite

**Comment by paragonie-security** [comment]
No, libsodium only uses Ed25519/X25519.

If you want something custom built, that's a service our company provides. Send us an email at info@paragonie.com if you'd rather not discuss the details on a public Github issue.

**Comment by issekeG** [comment]
I get this error when I try to login. can you tell me the cause?

[PHP-FPM    ] {"message":"Uncaught PHP Exception RangeException: \"Expected hexadecimal character\" at /var/www/app/vendor/paragonie/constant_time_encoding/src/Hex.php line 144","context":{"exception":{"class":"RangeException","message":"Expected hexadecimal character","code":0,"file":"/var/www/app/vendor/paragonie/constant_time_encoding/src/Hex.php:144"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2023-08-07T09:24:45.052271+00:00","extra":{}}
