### ISSUE TITLE
[RFC] Include the password expiration timestamp with the encrypted hash

### ISSUE THREAD

**Issue by sstok** [paragonie/halite#45]
This is an idea I came-up with a few days ago after reading https://paragonie.com/blog/2016/09/untangling-forget-me-knot-secure-account-recovery-made-simple

> However, even if you apply this mitigation, there's nothing preventing an attacker from just replacing one user's password hash with their own (unique constraints on the database column don't help here; simply change your own password then set the target's to your old password hash, for which you know the correct password).

To prevent someone from re-setting an expired password, would it make sense to include the expiration timestamp with the encrypted password-hash? 

With Halite the password is first crypto-hashed and then encrypted with a key.
If you include the expiration timestamp with the encrypted hash: `time-stamp:hash` -> encrypt, it would still be possible to re-set the password to a known hash, but after decryption the system will refuse the give an OK as the password is (eventually) expired.
And the attacker shouldn't know the encryption key, and thus is not able to create a correct result.

I'm no security expert, so I would like hear your opinion on this idea 👍

**Comment by paragonie-scott** [comment]
That would require password expiration to be a part of your policy.

I don't recommend "change your password every N days" as that just incentivizes users to use weak passwords they can remember easier after a change.

If this change were to be made, it would be implemented in an `ExpiringPassword` class rather than the mainline `Password` class.
