### ISSUE TITLE
FileAccessDenied: Resource is in w+b mode, which is not allowed.

### ISSUE THREAD

**Issue by marcoreni** [paragonie/halite#90]
After updating to 4.3.1 I'm getting an exception while trying to decrypt a resource.

Here is what I'm doing:
```php
$dataKey = // [...] retrieve EncryptionKey
$fileName = tempnam(sys_get_temp_dir(), 'tempfile'); // temporary target file
$resource = $entity->getTheResource(); // $entity is a Doctrine mapped object
File::decrypt($resource, $fileName, $dataKey);
```
The exception is `FileAccessDenied: Resource is in w+b mode, which is not allowed.` in `vendor/paragonie/halite/src/Stream/ReadOnlyFile.php (line 101)`

It seems that this commit is the culrpit:
https://github.com/paragonie/halite/commit/6c13dd05c25d148a8884715c39c5db4ecdc08a2e#diff-c35501cb3c448dc606defff8b2632864

I'm not sure how to retrieve the resource as read only, since I'm using Doctrine ORM to retrieve it from a database.

Moreover, this exception causes a second exception, `Undefined variable: readOnly` in `vendor/paragonie/halite/src/File.php (line 185)`, probably because the $readOnly file is never created and cannot therefore be closed.

**Comment by Nenglish7** [comment]
It will only accept r+b mode not w-b. We should not be giving write access.

**Comment by Nenglish7** [comment]
Basically a read only file.

**Comment by paragonie-scott** [comment]
`r+b` isn't allowed either, only `rb`. The guarantees of `ReadOnlyFile` include mitigating TOCTOU attacks, and making the file handle read-only strengthens this.

I'm not sure what your Doctrine ORM based code is doing, since `getTheResource()` isn't found anywhere in [the Doctrine ORM source code](https://github.com/doctrine/doctrine2/search?utf8=%E2%9C%93&q=getTheResource&type=), so I'm not sure how much help I can be. Maybe @Ocramius would have some insight?

**Comment by paragonie-scott** [comment]
Short hack that *might* work:

```diff
- File::decrypt($resource, $fileName, $dataKey);
+ $metadata = \stream_get_meta_data($resource);
+ $readOnlyResource = \fopen($metadata['uri'], 'rb');
+ File::decrypt($readOnlyResource, $fileName, $dataKey);
```

**Comment by marcoreni** [comment]
Unfortunately that did not work, since the resource is of type MEMORY.

`getTheResource` was just a pseudocode. Doctrine is a bit more complicated than that, but the main concept is that the data is persisted in a database (in my case, in a postgresql as bytea ) and then fetched by Doctrine and mapped internally to a resource. Therefore, the resource cannot be opened as readOnly (otherwise it wouldn't be possible to populate it with data in the first place, AFAIK).

I managed to get around the problem by saving the fetched resource to a tempFile and then pass the fileName to Halite. Definitely not nice, though. I'm now trying to see if Doctrine has a way to do this internally. 

```
$tempFilename = tempnam(sys_get_temp_dir(), 'temp');
$tempFile = fopen($tempFn, 'w+');
stream_copy_to_stream($resource, $tempFile);
fclose($tempFile);

File::decrypt($tempFilename, $fileName, $dataKey);
```

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/halite/commit/6ffa1fd7b95cbe9388129471e35d6954c3bb0a4a introduces a `MutableInputFile` type. I'm updating the `File` class to accept stream objects directly instead of creating them. This will let you pass a `MutableInputFile` of the resource if you wish to opt out of TOCTOU protection.

**Comment by paragonie-scott** [comment]
If you update to v4.4.0, this is fixed. https://github.com/paragonie/halite/releases/tag/v4.4.0

```diff
- File::decrypt($resource, $fileName, $dataKey);
+ File::decrypt(new WeakReadOnlyFile($resource), $fileName, $dataKey);
```

(Don't forget the namespace import at the top.)
